### ISSUE TITLE
how to set imGui Window bg with an png picture by xxImage

### ISSUE THREAD

**Issue by hanson1977** [metarutaiga/xxImGui#1]
hi,I now write windows tests with xxImGui, want set window bg picture with xxImage but failed.
steps  as flow  but failed:

1. load png faile with stbi_load
  unsigned char *data = stbi_load(pngfile, &w, &h, &n, 4);
2. create 2d image with xxImage
    xxImagePtr image = xxImage::Create2D(0, w, h, 1);	
3. copy the png content to xxImage instance
    memcpy((void*)image.get(), data, image->Size(1));
4. Update it in DearImGui::Update
       ImGui::Begin("helloworld");
       img->Update(Renderer::g_device);
      ImGui::End();

what's the problem with my code? please help!! thanks

**Comment by metarutaiga** [comment]
Sorry, the xxGraphicPlus is not finish yet.
You can try this
```
ImGui::Image((ImTextureID)img->GetTexture(), ImVec2(w, h));
```
or see the experimental branch
https://github.com/metarutaiga/xxImGui/blob/86203471e214258c8f4d1df547b9aa3445fe65c6/plugin/yuv/yuv.cpp#L40
and
https://github.com/metarutaiga/xxImGui/blob/86203471e214258c8f4d1df547b9aa3445fe65c6/plugin/yuv/yuv.cpp#L606

**Comment by hanson1977** [comment]
> Sorry, the xxGraphicPlus is not finish yet.
> You can try this
> 
> ```
> ImGui::Image((ImTextureID)img->GetTexture(), ImVec2(w, h));
> ```
> 
> or see the experimental branch
> https://github.com/metarutaiga/xxImGui/blob/86203471e214258c8f4d1df547b9aa3445fe65c6/plugin/yuv/yuv.cpp#L40
> 
> 
> and
> https://github.com/metarutaiga/xxImGui/blob/86203471e214258c8f4d1df547b9aa3445fe65c6/plugin/yuv/yuv.cpp#L606

thank you so much!!!
